# Generated by Django 4.0 on 2024-08-02 14:50

import backend.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20)),
                ('parcela_catastral', models.CharField(max_length=50)),
                ('sup_total', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sup_regable', models.DecimalField(decimal_places=4, max_digits=10)),
                ('num_olivos', models.IntegerField()),
                ('concesion', models.CharField(max_length=100)),
                ('toma_agua', models.CharField(max_length=100)),
                ('suelo', models.CharField(max_length=100)),
                ('paraje', models.CharField(max_length=100)),
                ('fecha_alta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ComunidadRegantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('cif', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=15, null=True)),
                ('email_alternativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre_entidad', models.CharField(max_length=100)),
                ('numero_banco', models.CharField(max_length=4)),
                ('numero_sucursal', models.CharField(max_length=4)),
                ('digito_control', models.CharField(max_length=2)),
                ('numero_cuenta', models.CharField(max_length=10)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_movil_contacto', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Comunidad de Regantes',
                'verbose_name_plural': 'Comunidades de Regantes',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='UsoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_uso', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sistema_riego', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_parcela', to='backend.cultivo')),
                ('parcela', models.ForeignKey(default=backend.models.get_default_parcela, on_delete=django.db.models.deletion.CASCADE, related_name='usos_parcela', to='backend.caracteristicasparcela')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('usuarios', models.ManyToManyField(related_name='plots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=15, null=True)),
                ('email_alternativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre_entidad', models.CharField(max_length=100)),
                ('numero_banco', models.CharField(max_length=4)),
                ('numero_sucursal', models.CharField(max_length=4)),
                ('digito_control', models.CharField(max_length=2)),
                ('numero_cuenta', models.CharField(max_length=10)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_movil_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('comunidades_regantes', models.ManyToManyField(related_name='miembros', to='backend.ComunidadRegantes')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='FaseCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=100)),
                ('kc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nap', models.IntegerField()),
                ('prof_rad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('das_inicio', models.IntegerField()),
                ('porcentaje_almacen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases_cultivo', to='backend.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='DatosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dato', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=255)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_adicionales', to='backend.caracteristicasparcela')),
            ],
        ),
        migrations.CreateModel(
            name='ControlPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(max_length=50)),
                ('numero_factura', models.CharField(max_length=50)),
                ('pagador', models.CharField(max_length=100)),
                ('vencimiento', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_pagos', to='backend.caracteristicasparcela')),
            ],
        ),
        migrations.CreateModel(
            name='ContadoresMedidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.CharField(max_length=20)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('lectura_max', models.IntegerField()),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contadores_medidas', to='backend.caracteristicasparcela')),
            ],
        ),
        migrations.CreateModel(
            name='Consumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50)),
                ('periodo_facturacion', models.CharField(max_length=50)),
                ('volumen_medido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='backend.caracteristicasparcela')),
            ],
        ),
        migrations.AddField(
            model_name='caracteristicasparcela',
            name='plot',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='backend.plot'),
        ),
    ]
