# Generated by Django 4.0 on 2024-08-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('asunto', models.CharField(max_length=255)),
                ('localizacion', models.CharField(max_length=255)),
                ('dirig', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_documentos', to='auth.user')),
            ],
            options={
                'verbose_name': 'Registro de Documento',
                'verbose_name_plural': 'Registros de Documentos',
            },
        ),
    ]
