# Generated by Django 4.0 on 2024-08-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_registrodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodocumento',
            name='entrada_salida',
            field=models.BooleanField(default=True),
        ),
    ]
