# Generated by Django 4.0 on 2024-08-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_lineafactura_options_alter_lineafactura_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineafactura',
            name='total_sin_iva',
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_facturado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='iva',
            field=models.DecimalField(choices=[(10, '10%'), (21, '21%'), (0, '0%')], decimal_places=2, max_digits=4),
        ),
    ]
