# Generated by Django 4.0 on 2024-08-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_lineafactura_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineafactura',
            name='iva',
            field=models.IntegerField(choices=[(10, '10%'), (21, '21%'), (0, '0%')]),
        ),
    ]
